spring.application.name=festo-webapp-backend
# ===================================================================
# Configuração do Banco de Dados (Projeto Festo - Porta 5433)
# ===================================================================

# URL de conexão apontando para a NOVA porta 5433 e o NOVO banco 'festo_db'
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# ===================================================================
# Configuração do JPA e Hibernate
# ===================================================================

# 'update' vai criar as tabelas automaticamente no seu novo banco
spring.jpa.hibernate.ddl-auto=update

# Dialeto do PostgreSQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Útil para ver no console os comandos SQL que o Hibernate está executando
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
